# .github/workflows/dev-deploy.yaml
name: Dev Polybot Service Deployment

on:
  push:
    branches:
      - dev

env:
  EC2_PUBLIC_IP: 16.16.67.19
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          scp -r -i mykey.pem /.github/workflows/dev-deploy.yaml ubuntu@16.16.67.19:/home/ubuntu/Polybot/.github/workflows
          scp -r -i  mykey.pem /polybot/bot.py ubuntu@EC2_PUBLIC_IP:/home/ubuntu/Polybot/polybot
          scp -r -i  mykey.pem /polybot/img_proc.py ubuntu@EC2_PUBLIC_IP:/home/ubuntu/Polybot/polybot
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@EC2_PUBLIC_IP
          
