# .github/workflows/prod-deploy.yaml
name: Prod Polybot Service Deployment

on:
  push:
    branches:
      - production

env:
  EC2_PUBLIC_IP: 51.20.118.199
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          scp -r -i  mykey.pem /polybot/bot.py ubuntu@EC2_PUBLIC_IP:/home/ubuntu/Polybot/PolybotServicePython/polybot
          scp -r -i  mykey.pem /polybot/img_proc.py ubuntu@EC2_PUBLIC_IP:/home/ubuntu/Polybot/PolybotServicePython/polybot
          ssh -i mykey.pem ubuntu@EC2_PUBLIC_IP
